// <auto-generated />
namespace Otv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changethedanmuvaluecontentlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changethedanmuvaluecontentlength));
        
        string IMigrationMetadata.Id
        {
            get { return "201609290648203_change the danmu value content length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
